language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2

gemfile:
  - Gemfile
  - gemfiles/Gemfile.fluentd-0.10.58
  - gemfiles/Gemfile.fluentd-0.12

os:
  - linux
  - osx

before_install:
  - gem update bundler

script: bundle exec rake test

sudo: false

matrix:
  exclude:
    - rvm: 2.0.0
      os: osx
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1
      os: osx
      gemfile: gemfiles/Gemfile.fluentd-0.10.58
    - rvm: 2.1
      os: osx
      gemfile: gemfiles/Gemfile.fluentd-0.12
    - rvm: 2.2
      os: osx
