language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2

os:
  - linux
  - osx

gemfile:
  - Gemfile

before_install:
  - gem update bundler

script: bundle exec rake test

sudo: false

matrix:
  exclude:
    - rvm: 2.2
      os: osx
