language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2

env:
  - "fluentd=0.12.22"
  - "fluentd=0.10.53"

os:
  - linux
  - osx

gemfile:
  - Gemfile

before_install:
  - gem update bundler

script: bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: 2.2
      os: osx
